import { Button } from "@/components/ui/button";
import { ArrowDown, Sparkles, Target, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";

interface HeroSectionProps {
  onGetStarted?: () => void;
}

export default function HeroSection({ onGetStarted }: HeroSectionProps) {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  const scrollToRoadmapBuilder = () => {
    document.getElementById('roadmap-builder')?.scrollIntoView({ behavior: 'smooth' });
    onGetStarted?.();
  };

  return (
    <section className="text-center mb-16 max-w-6xl mx-auto relative overflow-hidden py-20">
      {/* Enhanced animated background elements */}
      <div className="absolute inset-0 -z-10">
        <div className="floating absolute top-20 left-10 opacity-30">
          <Sparkles className="h-8 w-8 text-purple-400 glow-pulse" />
        </div>
        <div className="floating absolute top-32 right-16 opacity-30" style={{ animationDelay: '2s' }}>
          <Target className="h-6 w-6 text-blue-400 glow-pulse" />
        </div>
        <div className="floating absolute bottom-40 left-20 opacity-30" style={{ animationDelay: '4s' }}>
          <TrendingUp className="h-7 w-7 text-emerald-400 glow-pulse" />
        </div>
        <div className="floating absolute top-1/2 right-1/4 opacity-20" style={{ animationDelay: '6s' }}>
          <Sparkles className="h-5 w-5 text-pink-400 glow-pulse" />
        </div>
      </div>

      {/* Main content */}
      <div className={`${isVisible ? 'slide-up' : 'opacity-0'}`}>
        <div className="mb-8">
          <div className="inline-flex items-center px-6 py-3 bg-gradient-to-r from-purple-500/20 to-blue-500/20 rounded-full mb-6 backdrop-blur-glass border border-purple-500/30 shimmer">
            <Sparkles className="h-4 w-4 text-purple-300 mr-2 glow-pulse" />
            <span className="text-sm font-medium text-purple-200">Your Career Journey Starts Here</span>
          </div>
        </div>

        <h1 className="text-5xl md:text-7xl font-extrabold mb-8 leading-tight">
          <span className="block text-white mb-2">Confused about your</span>
          <span className="gradient-text block">career path?</span>
        </h1>

        <p className="text-xl md:text-2xl text-gray-300 mb-12 max-w-3xl mx-auto leading-relaxed">
          Discover your perfect career roadmap with AI-powered guidance. 
          <br />
          <span className="font-semibold text-white">Transform confusion into clarity.</span>
        </p>

        {/* Enhanced feature highlights */}
        <div className={`grid md:grid-cols-3 gap-6 mb-12 max-w-4xl mx-auto ${isVisible ? 'fade-in' : 'opacity-0'}`} style={{ animationDelay: '0.3s' }}>
          <div className="backdrop-blur-glass rounded-xl p-6 card-hover border border-purple-500/20 shimmer">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-blue-500 rounded-lg flex items-center justify-center mx-auto mb-4 pulse-glow">
              <Sparkles className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-white mb-2">AI-Powered</h3>
            <p className="text-sm text-gray-300">Personalized roadmaps generated by advanced AI</p>
          </div>

          <div className="backdrop-blur-glass rounded-xl p-6 card-hover border border-emerald-500/20 shimmer">
            <div className="w-12 h-12 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-lg flex items-center justify-center mx-auto mb-4 pulse-glow" style={{ animationDelay: '0.5s' }}>
              <Target className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-white mb-2">Goal-Focused</h3>
            <p className="text-sm text-gray-300">Clear milestones and actionable steps</p>
          </div>

          <div className="backdrop-blur-glass rounded-xl p-6 card-hover border border-orange-500/20 shimmer">
            <div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-red-500 rounded-lg flex items-center justify-center mx-auto mb-4 pulse-glow" style={{ animationDelay: '1s' }}>
              <TrendingUp className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-white mb-2">Track Progress</h3>
            <p className="text-sm text-gray-300">Monitor your career journey and achievements</p>
          </div>
        </div>

        {/* Enhanced CTA Button */}
        <div className={`${isVisible ? 'fade-in' : 'opacity-0'}`} style={{ animationDelay: '0.6s' }}>
          <Button 
            onClick={scrollToRoadmapBuilder}
            className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white px-8 py-4 text-lg font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105 mb-4 shimmer glow-pulse"
          >
            Start Your Journey
          </Button>
          
          <div className="bounce-gentle inline-block">
            <Button 
              onClick={scrollToRoadmapBuilder}
              variant="ghost"
              className="text-gray-400 hover:text-purple-300 p-2 block mx-auto hover:bg-white/10"
            >
              <ArrowDown className="h-6 w-6" />
            </Button>
          </div>
        </div>
      </div>

      {/* Enhanced gradient overlay */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-background/50 -z-5 pointer-events-none" />
    </section>
  );
}
