import { Button } from "@/components/ui/button";
import { ArrowDown, Sparkles, Target, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";

interface HeroSectionProps {
  onGetStarted?: () => void;
}

export default function HeroSection({ onGetStarted }: HeroSectionProps) {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  const scrollToRoadmapBuilder = () => {
    document.getElementById('roadmap-builder')?.scrollIntoView({ behavior: 'smooth' });
    onGetStarted?.();
  };

  return (
    <section className="text-center mb-16 max-w-6xl mx-auto relative overflow-hidden">
      {/* Animated background elements */}
      <div className="absolute inset-0 -z-10">
        <div className="floating absolute top-20 left-10 opacity-20">
          <Sparkles className="h-8 w-8 text-purple-500" />
        </div>
        <div className="floating absolute top-32 right-16 opacity-20" style={{ animationDelay: '2s' }}>
          <Target className="h-6 w-6 text-blue-500" />
        </div>
        <div className="floating absolute bottom-40 left-20 opacity-20" style={{ animationDelay: '4s' }}>
          <TrendingUp className="h-7 w-7 text-emerald-500" />
        </div>
      </div>

      {/* Main content */}
      <div className={`${isVisible ? 'slide-up' : 'opacity-0'}`}>
        <div className="mb-8">
          <div className="inline-flex items-center px-4 py-2 bg-gradient-to-r from-purple-100 to-blue-100 rounded-full mb-6 backdrop-blur-glass">
            <Sparkles className="h-4 w-4 text-purple-600 mr-2" />
            <span className="text-sm font-medium text-purple-700">Your Career Journey Starts Here</span>
          </div>
        </div>

        <h1 className="text-5xl md:text-7xl font-extrabold mb-8 leading-tight">
          <span className="block text-gray-900 mb-2">Confused about your</span>
          <span className="gradient-text block">career path?</span>
        </h1>

        <p className="text-xl md:text-2xl text-gray-600 mb-12 max-w-3xl mx-auto leading-relaxed">
          Discover your perfect career roadmap with AI-powered guidance. 
          <br />
          <span className="font-semibold text-gray-800">Transform confusion into clarity.</span>
        </p>

        {/* Feature highlights */}
        <div className={`grid md:grid-cols-3 gap-6 mb-12 max-w-4xl mx-auto ${isVisible ? 'fade-in' : 'opacity-0'}`} style={{ animationDelay: '0.3s' }}>
          <div className="backdrop-blur-glass rounded-xl p-6 hover:scale-105 transition-transform duration-300">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-blue-500 rounded-lg flex items-center justify-center mx-auto mb-4 pulse-glow">
              <Sparkles className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-gray-900 mb-2">AI-Powered</h3>
            <p className="text-sm text-gray-600">Personalized roadmaps generated by advanced AI</p>
          </div>

          <div className="backdrop-blur-glass rounded-xl p-6 hover:scale-105 transition-transform duration-300">
            <div className="w-12 h-12 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-lg flex items-center justify-center mx-auto mb-4 pulse-glow" style={{ animationDelay: '0.5s' }}>
              <Target className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-gray-900 mb-2">Goal-Focused</h3>
            <p className="text-sm text-gray-600">Clear milestones and actionable steps</p>
          </div>

          <div className="backdrop-blur-glass rounded-xl p-6 hover:scale-105 transition-transform duration-300">
            <div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-red-500 rounded-lg flex items-center justify-center mx-auto mb-4 pulse-glow" style={{ animationDelay: '1s' }}>
              <TrendingUp className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-gray-900 mb-2">Track Progress</h3>
            <p className="text-sm text-gray-600">Monitor your career journey and achievements</p>
          </div>
        </div>

        {/* CTA Button */}
        <div className={`${isVisible ? 'fade-in' : 'opacity-0'}`} style={{ animationDelay: '0.6s' }}>
          <Button 
            onClick={scrollToRoadmapBuilder}
            className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white px-8 py-4 text-lg font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105 mb-4"
          >
            Start Your Journey
          </Button>
          
          <div className="bounce-gentle inline-block">
            <Button 
              onClick={scrollToRoadmapBuilder}
              variant="ghost"
              className="text-gray-500 hover:text-gray-700 p-2 block mx-auto"
            >
              <ArrowDown className="h-6 w-6" />
            </Button>
          </div>
        </div>
      </div>

      {/* Subtle gradient overlay */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-white/50 -z-5 pointer-events-none" />
    </section>
  );
}
